# Random Forest

Random forest is a `Supervised ML algorithm`. Like you can already see from it's name, it create a forest and makes it somehow random. The forest it built, is an ensemble of decision trees, most of the time trained with the 'bagging' method. the general idea of the bagging method is that a coombination of learning models increases the overall result. 

To Say it in simple words: random forest builts multiple decision trees and mergs them together to get a more accurate and stable prediction.

In [1]:
# import libraries :
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import  mean_squared_error, mean_absolute_error, r2_score

In [2]:
# load the data 
df = sns.load_dataset("tips")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [3]:
# encode feature which are categorial or object using for loop
le = LabelEncoder()

# for col in df.select_dtypes(include = ['category', 'object']):
#     df[col] = le.fit_transform(df[col])

# method 2
for i in df.columns:
    if df[i].dtypes == 'object' or df[i].dtypes == 'category':
        df[i] = le.fit_transform(df[i])
df.head()

   total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    2     0     2
1       10.34  1.66    1       0    2     0     3
2       21.01  3.50    1       0    2     0     3
3       23.68  3.31    1       0    2     0     2
4       24.59  3.61    0       0    2     0     4

In [4]:
# split the data into X and y for classification
X = df.drop('sex', axis = 1)
y = df['sex']

# train test split the data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42 )

# create , train and predict the model 
model = RandomForestClassifier(n_estimators = 200, random_state = 42)

# train the model 
model.fit(X_train, y_train)

# predict the model
y_predict = model.predict(X_test)

# Evaluate the model
print(confusion_matrix(y_test, y_predict))
print(classification_report(y_test, y_predict))

[[ 7 12]
 [ 7 23]]
              precision    recall  f1-score   support

           0       0.50      0.37      0.42        19
           1       0.66      0.77      0.71        30

    accuracy                           0.61        49
   macro avg       0.58      0.57      0.57        49
weighted avg       0.60      0.61      0.60        49

In [5]:
# use random forest for regression task


# split the data into X and y for classification
X = df.drop('tip', axis = 1)
y = df['tip']

# train test split the data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42 )

# create , train and predict the model 
model = RandomForestRegressor(n_estimators = 300, random_state = 42)

# train the model 
model.fit(X_train, y_train)

# predict the model
y_predict = model.predict(X_test)

# Evaluate the model
print(mean_squared_error(y_test, y_predict))
print(mean_absolute_error(y_test, y_predict))
print(r2_score(y_test, y_predict))
print(np.sqrt(mean_squared_error(y_test, y_predict)))

0.9522409153061234
0.7738986394557825
0.2381898041844317
0.9758283226603558